### ISSUE TITLE
Doesn't work in Angular 1.3.3

### ISSUE THREAD

**Issue by ghost** [nervgh/angular-file-upload#307]
After migrating from Angular 1.2.16 to 1.3.3, this directive has stopped working entirely.
I get the following error when I upload a file:

``` javascript
Uncaught TypeError: undefined is not a function angular.js:8488Yb
angular.js:8488(anonymous function) angular-file-upload.js:1319r 
angular.js:322g._transformResponse angular-file-upload.js:1319c.onload angular-file-
upload.js:1319
```

Please update on how to fix this.

**Comment by nervgh** [comment]
This looks like solved --> https://github.com/nervgh/angular-file-upload/issues/307#issuecomment-65243230
